### PR TITLE
fix: copy yarn directory from nodejs image

### LINKED ISSUE #1: Yarn does not working
This is really cool idea. But why doesn't yarn work? When running the following command even though yarn binary is copied over yarn binary doesn't work.

```bash
docker run -it --rm  thisismydesign/ruby-node-alpine:3.0.3-16.13.0-alpine yarn -v
```

### PR DESCRIPTION
**Pull request by codezninja**
Yarn binary is a symlink to a directory in `/opt`. Copying that directory as well will fix yarn in these images.

Fixes #1

### CODE REVIEW

**Comment by thisismydesign** [comment]
Thank you @codezninja! Could you add a check for yarn as well to the CI here? https://github.com/thisismydesign/ruby-node-alpine/blob/4a7c53c19bd6fe49441a7f86050d85743d415c13/.github/workflows/ci.yml#L32

Please enable github actions on your repo so the CI can run. If it's green I'm happy to merge.

**Comment by codezninja** [comment]
done

**Comment by thisismydesign** [comment]
Thanks! Could you also enable github actions on your fork so we can check the CI?

**Comment by codezninja** [comment]
@thisismydesign so github actions is already enabled on fork. If you want to see the CI on this pr you'll have to enable github actions on forked prs I believe. https://github.com/codezninja/ruby-node-alpine/actions/runs/2180432661

You might also have to enable to the workflow to run on `pr` not just `push`

**Comment by thisismydesign** [comment]
You're right, thanks. I'll do that, meanwhile I'll merge your changes. ~~I'm on holiday so it might be some time until a release but you should be able to use this from the branch.~~ Nevermind, should be good to go once the CI ran.

**Review by thisismydesign — APPROVED** [review]

**Pull request merged**
